services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mp3_rabbitmq
    ports:
      - "5672:5672"    # used by your Python: pika
      - "15672:15672"  # management UI at http://localhost:15672 (guest/guest)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:17.6
    container_name: mp3_postgres
    environment:
      POSTGRES_DB: mp3manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_data:
